export default {
  ADD_TODO: "ADD_TODO",
  REMOVE_TODO: "REMOVE_TODO",
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  REAMOVE_TO_WISHLIST: "REAMOVE_TO_WISHLIST",
  LOGOUT: "LOGOUT",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOADING_START: "LOADING_START",
  FATCH_PRODUCTS: "FATCH_PRODUCTS",
  IS_FAVORITE: "IS_FAVORITE",
  GET_DETAIL: "GET_DETAIL",
  UPLOAD_SUCCESS: "UPLOAD_SUCCESS",
  UPLOAD_FAIL: "UPLOAD_FAIL",
  PRICE_FILTER: "PRICE_FILTER"

  // COMPLETE_TODO: 'COMPLETE_TODO',
  // COMPLETE_ALL: 'COMPLETE_ALL',
  // REMOVE_COMPLETED: 'REMOVE_COMPLETED',
};
